### ISSUE TITLE
Cursor 'pointer' missing

### ISSUE THREAD

**Issue by xrobau** [sensu/uchiwa-web#4]
This is a User Experience issue more than anything else.

When the mouse pointer is over something that can be clicked on, there should be some css along the lines of:

.ng-binding:hover {
  cursor: pointer;
}

However, there's some things that AREN'T clickable that have the ng-binding class (well, at least the 'h2' class at the top of the page)

**Comment by palourde** [comment]
Moved to https://github.com/sensu/uchiwa/issues/270
